### ISSUE TITLE
RFC: Restructure package into modules

### ISSUE THREAD

**Issue by susnux** [nextcloud-libraries/nextcloud-files#1015]
Currently everything is exported from the main (and only) entry point.
But this library of helpers keeps growing.

So we could structure this package into different modules, to have a logical structure.
It would also benefit the tree shaking as e.g. dependencies with global state would be removed if not needed (for example the webdav client would completly removed if only `orderBy` is used).

So I could imagine to split off dav tools into `@nextcloud/files/dav`, we could then also remove the `dav` prefix for all of those functions.

Other module could be `@nextcloud/files/utils` for our various general purpose file utils.

This would also benefit the Typedoc documentation by splitting it into multiple modules (better overview).

**Comment by skjnldsv** [comment]
Looks like a good idea!! :)
