### ISSUE TITLE
Ignoring .git folder

### ISSUE THREAD

**Issue by henrysheehy** [nextcloud-libraries/nextcloud-files#1039]
Dear concerned,

How can I ignore .git folders in the NC data directory?

Some users choose to sync these, and they're bringing up symlink errors in the log. 

To be clear, I would like NC to ignore these files on the server.

Best regards,
Henry

**Comment by skjnldsv** [comment]
Hi, wrong location to ask, I would have checked the forums
Nonetheless: https://docs.nextcloud.com/server/28/admin_manual/configuration_server/config_sample_php_parameters.html#blacklisted-files
