### ISSUE TITLE
wrong filename returned by davResultToNode? 

### ISSUE THREAD

**Issue by StCyr** [nextcloud-libraries/nextcloud-files#1041]
Hello,

I'm the author of https://github.com/nextcloud-libraries/nextcloud-files/pull/1007

I'm wondering if there's not a bug in `davResultToNode`

Let me explain:

I've an app which register a file action with `registerFileAction`.

When I call this action, it does its thing and then emits a `files:node:updated` event to get the fileList updated (this is done exactly as in the PR mentioned above).

Fine till now...

But, now, if I try to call my action again, I get a HTTP 500 error....

After investigation, it appears that it's because the filename attribute of the file has changed: it's now prepended with `/files/${userid}` (while it wasn't before -ie:when I'd just opened the https://localhost/nc-latest/index.php/apps/files/files?dir=/ URL-)

Further analysis shows that this filename is set by `davResultToNode`; Here's an output of my js debugger when I emit the `files:node:updated` event:

```
"files:node:updated" event emitted for node: 
Object { _data: {…}, _attributes: Proxy, _knownDavService: /(remote|public)\.php\/(web)?dav/i }
​__ob__: Object { shallow: false, mock: false, vmCount: 0, … }
​_attributes: Proxy { <target>: {…}, <handler>: {…} }
​​<target>: Object { filename: Getter & Setter, basename: Getter & Setter, lastmod: Getter & Setter, … }
​​​__ob__: Object { shallow: false, mock: false, vmCount: 0, … }
​​​basename: 
​​​"comments-unread": 
​​​etag: 
​​​favorite: 
​​​fileid: 
​​​filename: "/files/admin/Lettre_-_Prime_dassurance_soins_dentaires-2.PDF"
​​​getcontentlength: 
```

Does it makes sense to you? Looks like a bug to me....

# Steps to reproduce

I'll try to write down here steps that should make you able to reproduce this bug:

1. Create a fileAction that simply does `console.log(file.attributes.filename)` and use the code in #1007 to update the file list;
2. Run this action from a file's action menu;
4. Observe in you browser's the value of `file.attributes.filename`;
5. Run this action directly again;
6. Observe in you browser's console that `file.attributes.filename` has changed;
7. (optional) Refresh the page;
8.  (optional) Run his action again;
9.  (optional) Observe in you browser's console that `file.attributes.filename` is back to what it was at point 1;

**Comment by skjnldsv** [comment]
`file.attributes.filename` is not an official attribute
use `file.basename` please https://nextcloud-libraries.github.io/nextcloud-files/classes/File.html#basename

**Comment by StCyr** [comment]
@skjnldsv ,

I have an example where basename is not available 

![image](https://github.com/user-attachments/assets/98c18ba5-9fff-4bcf-9b8d-77f3ad37ebae)

so that's a bit of an issue to follow your recommendation 😜 

Do you want me to open a new issue?

**Comment by skjnldsv** [comment]
Basename cannot be removed https://github.com/nextcloud-libraries/nextcloud-files/blob/a738dbca51bd9ad79a5fdbd0caa2277146046a33/lib/files/node.ts#L106

How was this object created? Where are you seeing this?

**Comment by StCyr** [comment]
> How was this object created? Where are you seeing this?

from a public share page
