### ISSUE TITLE
arguments to FileAction.exec()

### ISSUE THREAD

**Issue by StCyr** [nextcloud-libraries/nextcloud-files#1045]
In https://nextcloud-libraries.github.io/nextcloud-files/classes/FileAction.html, are we sure the first argument is always a Node?

When you call such an action from the "Shares" view, the object passed is very different than from the object passed in the "Files" view.

It's a bit a shame what I'm doing now to get the proper directory name of the file:

```js
const action = function(file, view, dir) {
	let directory
	let file_name
	if (view.name === 'Shares') {
		file_name = file.attributes.path
		directory = file.attributes.path.match(/.*\//)[0].slice(0, -1)
		directory = directory.length ? directory: '/'
	} else {
		file_name = file.attributes.filename
		directory = dir
	}
	...
}
```

It would be good if we knew what attributes to expect for this object....

**Comment by skjnldsv** [comment]
The API is strict. The first argument is indeed a node.
But the sharing view uses a different API (not dav), so many attributes are missing.

Can you be more clear regarding the differences you're seeing?

**Comment by skjnldsv** [comment]
Just saw your code...
Please do not use attributes to get values that exists at the top level (like filename, path.... Etc)
Please read the available properties in the API documentation.
`node.basename`, `node.filename`, `node.source`.... etc


@susnux, see, this is why I was saying removing attributes that exists at the top level was a good idea 🙈😭

**Comment by skjnldsv** [comment]
@StCyr I did already mentioned that a few days ago in your other ticket btw 😉

https://github.com/nextcloud-libraries/nextcloud-files/issues/1041#issuecomment-2265363133

**Comment by susnux** [comment]
> removing attributes that exists at the top level

Waiting for cleanup with v4 😉

**Comment by StCyr** [comment]
> @StCyr I did already mentioned that a few days ago in your other ticket btw 😉
> 
> [#1041 (comment)](https://github.com/nextcloud-libraries/nextcloud-files/issues/1041#issuecomment-2265363133)

Yes, I saw it.

That's in another part of the code, another bug, here. And, I failed to look at the base attributes :sweat_smile: 

I'll try to refactor all this properly :-/

**Comment by skjnldsv** [comment]
@StCyr were you able to adjust the code to your use case? :)

**Comment by skjnldsv** [comment]
Also, will we see you at the [Nextcloud conference](https://nextcloud.com/conference-2024/) in September? :tada:

**Comment by StCyr** [comment]
Hello  @skjnldsv,

yes, I've been able to refactor the code properly, for what regards the file's name and directory.

But I still have issues retrieving other file's attributes.

For example "mtime" doesn't give consistent result when the file is accessed via the Files view compared to when accessed via the "Shares" view; for a share, "mtime" seems to always be the current time. And, when I try to retrieve the underlying file's attributes via node.attributes, its mtime is stored in an attribute called "item_mtime". So I still have to do translations depending from which view I'm accessing the file attributes... That's a bit dul....

Unfortunately, I won't be at the Nextcloud conference this year.... Maybe next year, depending how my career develops....

**Comment by skjnldsv** [comment]
> For example "mtime" doesn't give consistent result when the file is accessed via the Files view compared to when accessed via the "Shares" view;

It's possible that the Sharing API mapping to Node object is misbehaving. I just created a fix a few days ago. If you notice something, this is most likely not a problem with the @nextcloud/files api.
But you can check how we map the API response to a Node here: https://github.com/nextcloud/server/blob/96c827558611033ac35f6095b77ea04dca8044dd/apps/files_sharing/src/services/SharingService.ts#L67-L86

**Comment by StCyr** [comment]
@skjnldsv ,

I have an example where basename is not available 

![image](https://github.com/user-attachments/assets/98c18ba5-9fff-4bcf-9b8d-77f3ad37ebae)

so that's a bit of an issue to follow your recommendation 😜 

Do you want me to open a new issue?
