### ISSUE TITLE
Redeclaration of Node_2 class causes type incompatibilty

### ISSUE THREAD

**Issue by hschletz** [nextcloud-libraries/nextcloud-files#1127]
I migrated my application to use the new `dav` module introduced in v3.10, but ran into a problem:

`dist/dav.d.ts` contains a redeclaration of the `Node_2` class, which is a verbatim copy of the `Node_2` class from the main module. Some functions, like `resultToNode()`, return an instance of the class from the `dav` module. This causes Problems with code that expects a `Node` or `INode` from the main module:
```
 error TS2345: Argument of type 'Node_2' is not assignable to parameter of type 'INode'.
  The types returned by 'clone()' are incompatible between these types.
    Type 'Node_2' is not assignable to type 'import("<project_path>/node_modules/@nextcloud/files/dist/index").Node'.
      Types have separate declarations of a private property '_data'.
```
As said, the declarations are 100% identical, but Typescript sees them as different types. There are some ugly workarounds:

- Explicit cast: `resultToNode() as unknown as INode` (the intermediate cast to `unknown` is required to work around the perceived type incompatibility)
- Change consuming code to allow a `Node_2` from the `dav` module, but that looks more like an internal class name.

The redeclaration looks accidental to me. Should't there be only the `Node_2` class from the main module?

Pseudocode to reproduce:
```ts
import { INode } from '@nextcloud/files'
import { resultToNode } from '@nextcloud/files/dav'

function test(node: INode) // same problem with Node
{
    return node
}

const node = resultToNode(...)
test(node) // results in above error
```

**Comment by skjnldsv** [comment]
AH! I encountered the EXACT issue yesterday, couldn't fid the time to investigate :)
If you have a fix ready, feel free to send a PR :pray:

**Comment by skjnldsv** [comment]
Guessing this is coming from https://github.com/nextcloud-libraries/nextcloud-files/pull/1118 ? :thinking:

**Comment by hschletz** [comment]
Sorry, this is beyond my skills... I think the problem comes from the way the types are imported in the dav code:
```ts
import type { Node } from '../files/node'
```
This seems to make the type part of the dav module, thus ending up replicated in `dav.d.ts`. Instead, the output file should import the type from the main module, like this:
```ts
import { Node } from '@nextcloud/files'
```
Imports are generated only for references to external packages. I don't know how to do that for code from the same package, but that looks to me like a common task for developing library code.

**Comment by skjnldsv** [comment]
Hey!

Can you try with this instead?

```ts
import type { Node } from '@nextcloud/files'
import { resultToNode } from '@nextcloud/files/dav'

function test(node: Node) // same problem with Node
{
    return node
}

const node = resultToNode(...)
test(node) 
```

**Comment by hschletz** [comment]
Still does not work for me. I have no experience in testing local libraries. Anything wrong with these steps?
```shell
cd $HOME
git clone https://github.com/nextcloud-libraries/nextcloud-files.git
cd nextcloud-files
git checkout fix/imports 
npm run build
cd $HOME/my-project
npm install --no-save $HOME/nextcloud-files/
```
Creating your test code in my project directory, and passing some compatible argument to resultToNode(), still gives this TS error:
```
src/lib/test.ts:16:6 - error TS2345: Argument of type 'Node_2' is not assignable to parameter of type 'import("$HOME/nextcloud-files/dist/index").Node'.
  Types have separate declarations of a private property '_data'.

16 test(node)
        ~~~~
```
As you can see from the message, the module is correctly loaded from the local path.

My real code also gives the same error as before.

**Comment by skjnldsv** [comment]
@ShGKme @susnux for when you are back :see_no_evil: 
I don't get it
