### ISSUE TITLE
Refresh current folder view

### ISSUE THREAD

**Issue by Raudius** [nextcloud-libraries/nextcloud-files#845]
What would be the way to refresh the current directory in the files app?

In my app I dont know if/what files have changed so I just need to do a full refresh.

Previously I would use this 

```js
const fileList = OCA.Files?.App?.fileList ?? OCA?.Sharing?.PublicApp?.fileList
if (!fileList) {
  return
}
fileList.changeDirectory(fileList.getCurrentDirectory(), true, true)
```
https://github.com/Raudius/files_scripts/blob/v3.0.0/src/files.ts#L3

**Comment by skjnldsv** [comment]
We could make you trigger a change on the current folder and have the main view reload, I think that would make sense :thinking:

**Comment by Raudius** [comment]
Yes that would be perfect. How could I go about doing it?

**Comment by skjnldsv** [comment]
I would add a subscribe to the event here
https://github.com/nextcloud/server/blob/7cc649661863fb4b42b994221fd678529ebb1de2/apps/files/src/views/FilesList.vue#L402-L404


Something like this?

```ts
mounted() {
	subscribe('files:node:updated', this.onUpdatedNode)
},
methods: {
	// Refresh the current folder on update
	onUpdatedNode(node) {
		if (node.fileid === this.currentFolder.fileid) {
			this.fetchContent()
		}
	}
}
```
