### ISSUE TITLE
`registerFileAction` does not work on folders

### ISSUE THREAD

**Issue by Raudius** [nextcloud-libraries/nextcloud-files#846]
Previously, file actions registered with `OCA.Files.fileActions.registerAction` would also appear in the context menu for folders. 

Unless I am missing something `registerFileAction` does not register the action for folders.

**Comment by skjnldsv** [comment]
It does, it depends what conditions you added?
Please share some code

**Comment by Raudius** [comment]
Ah yeah, I made a mistake. All good :)
