### ISSUE TITLE
Access to selected files and favourites

### ISSUE THREAD

**Issue by mwinkens** [nextcloud-libraries/nextcloud-files#883]
Currently this library doesn't support access to selected files and favorites.
Since the documentation is a bit unclear (or work in progress), is there a way to get access to them?
I am talking about App access (instead of WebDAV access)

related: https://github.com/nextcloud/circles/issues/1434

**Comment by skjnldsv** [comment]
Hey, can you clarify what you mean?
The issue you linked has nothing to do with this library :)

**Comment by skjnldsv** [comment]
@mwinkens thanks!
`OCA.Files.FileList` was a private API that developers should not have relied upon.
Now if you want to interact with the Files list, there are multiple offical ways to do so.

Can you describe your use case please?
Do you have an app or some code to show us?

This library will not do anything for you, it's just shipping APIs and methods to help you achieve your goals faster.

**Comment by skjnldsv** [comment]
I see! Thanks for explaining.
From the multi-select action, you are getting all the data you need as a [Node](https://nextcloud-libraries.github.io/nextcloud-files/classes/Node.html). From then you can do whatever you want with them (get their fileid and send that to your backend controller for example)

> enter some metadata (in a tab in a fileview) and press publish in order to create deposits at b2share.

I think this is the issue, I don't understand why you're going for a sidebar Tab, I would open a Modal after clicking the `Publish to B2` action, you will clean up your code and you will not lose the context of the user's selection of files :)

**Comment by mwinkens** [comment]
I agree, I should switch to a modal there. How do I register a multi-select action? All i can currently do is register a FileAction. 

But even going from there, I would still need to find out, if the user selected **multiple files** or not. I could get the node of the currently file I clicked and upload it, but not of multiple.

I really appreciate your input, thank you!
