### ISSUE TITLE
Make fileActions available for shares

### ISSUE THREAD

**Issue by StCyr** [nextcloud-libraries/nextcloud-files#964]
It might be great if Nextcloud Apps could create fileActions to be available for shared files

use case is the [SignLive](https://apps.nextcloud.com/apps/signlive) app where we would like to be able to let guests sign pdf files

**Comment by skjnldsv** [comment]
What do you mean shared files? You mean in public view mode ?

**Comment by StCyr** [comment]
hmmm I probably mean that :laughing: 

I mean files that are shared with unauthenticated users, like when they are shared with a link... I think it relates to the following route in app file_sharing:

```
                [
                        'name' => 'Share#showShare',
                        'url' => '/s/{token}',
                        'verb' => 'GET',
                        'root' => '',
                ],
```

**Comment by susnux** [comment]
Needs: https://github.com/nextcloud/server/issues/42968

**Comment by skjnldsv** [comment]
Yeah, when it's done, you should be able to register file actions the very same way than the authenticated Files app.

**Comment by skjnldsv** [comment]
Closing as this is not related to this library and /theoritecally/ already supported

**Comment by susnux** [comment]
> I see [nothing] in @nextcloud/files registerFileAction seems to be related to share links.

`@nextclou/files` are helpers to work in general with files and especially to provide public API for the files app.
Currently the modern files list is only used for authenticated users, for public link shares still the legacy file list is used, so for public shares you would need to use the API you used with Nextcloud 27 and before.

We hope to switch the public shares file list to the modern file list soon.
